Add notifications to MatterMost
canonical/hotsos pull request #187
Opened 2021-11-04 22:07 UTC by nicolasbock

Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>

2021-11-04 22:07 UTC, nicolasbock commented
@dosaboy We need to add some secrets to this repo before this will work.

2021-11-05 15:19 UTC, sombrafam requested changes
There's a typo in the filename 'notofications'

2021-11-05 15:26 UTC, dosaboy requested changes
Filename should be notifications.yaml

2021-11-05 15:27 UTC, dosaboy requested changes

2021-11-05 15:27 UTC, dosaboy commented on .github/workflows/notofications.yaml
> +    branches: [ main ]
types: [ready_for_review]

2021-11-05 15:29 UTC, nicolasbock commented
Have another look please

2021-11-05 15:29 UTC, sombrafam approved these changes

2021-11-05 15:30 UTC, nicolasbock commented on .github/workflows/notofications.yaml
> +    branches: [ main ]
Done

2021-11-08 14:20 UTC, merged