Check for LP#1807628 and raise warning
canonical/hotsos pull request #398
Opened 2022-08-17 18:27 UTC by KellenRenshaw

This LP affects Bionic hosts, and since LXD is critical for the PCBs built on Bionic, this should be checked to advise the customer to upgrade.

2022-08-17 18:27 UTC, KellenRenshaw commented
Waiting for release from -proposed.

2022-09-05 14:04 UTC, dosaboy requested changes
Hi Kellen, thanks for the patch. Can we please get a unit test added for this?

2022-09-07 17:52 UTC, KellenRenshaw commented
@dosaboy Unit test added for the scenario(s).

2022-09-08 14:24 UTC, dosaboy approved these changes
lgtm

2022-09-08 14:24 UTC, merged