[plugin/ceph] Use the total used device size
canonical/hotsos pull request #407
Opened 2022-08-23 18:51 UTC by pponnuvel

The previous commit incorrectly used the total device
size instead of the total used size.

Signed-off-by: Ponnuvel Palaniyappan <pponnuvel@gmail.com>

2022-08-23 18:55 UTC, pponnuvel commented
The functional test fails because the metadata usage is really high ( > 99.96% - the fake_data_root seems to be from a cluster no  data).  I'll leave until @dosaboy gets back as editing ceph_osd_df_tree_--format_json-pretty in fake_data_root may not be good idea. If not, we'd need another approach to handle the functest failure.

2022-08-31 03:06 UTC, hillpd approved these changes
Looks good!

2022-09-06 15:18 UTC, dosaboy requested changes

2022-09-06 15:18 UTC, dosaboy commented on defs/scenarios/storage/ceph/ceph-mon/bluefs_size.yaml
> -        num_bad_meta_osds: '@checks.bluefs_osds_have_oversize_metadata.requires.value_actual:len'
i think its undocumented but there you can use :comma_join instead of :len

2022-09-06 15:18 UTC, dosaboy commented on defs/scenarios/storage/ceph/ceph-mon/bluefs_size.yaml
> -        Found {num_bad_meta_osds} Ceph OSDs with metadata size > {limit_percent}% of its
The second "OSDs" can be removed i think.

2022-09-06 15:37 UTC, pponnuvel commented
Addressed the comments @dosaboy

2022-09-06 15:39 UTC, merged