[kernel] Detect fsnotify related hangs in kernel logs (antivirus issues)
canonical/hotsos pull request #597
Opened 2023-05-08 07:33 UTC by nkshirsagar

Fixes #594

2023-05-09 10:05 UTC, mustafakemalgilor requested changes

2023-05-09 10:05 UTC, mustafakemalgilor commented on hotsos/core/plugins/kernel/kernlog/calltrace.py
> +                         r' fsnotify(\S+) security_file_open(\S+)'
`fanotify_handle_event` can be reached with another call path, i.e.:
```
 #0 [ffffb57ac3147b30] __schedule at ffffffff9cda0731
 #1 [ffffb57ac3147bc0] schedule at ffffffff9cda0cc5
 #2 [ffffb57ac3147bd0] fanotify_handle_event at ffffffff9c790008
 #3 [ffffb57ac3147c38] fsnotify at ffffffff9c78c213
 #4 [ffffb57ac3147cd0] do_dentry_open at ffffffff9c73ad0e
 #5 [ffffb57ac3147d00] path_openat at ffffffff9c74f72e
 #6 [ffffb57ac3147dd8] do_filp_open at ffffffff9c751a43
 #7 [ffffb57ac3147ee0] do_sys_open at ffffffff9c73c5e4
 #8 [ffffb57ac3147f38] do_syscall_64 at ffffffff9c40430b
 #9 [ffffb57ac3147f50] entry_SYSCALL_64_after_hwframe at ffffffff9ce000ad
 ```
 which won't fit the pattern above. IMO we can omit `security_file_open(\S+) vfs_open(\S+) do_filp_open(\S+)` part.

2023-05-17 08:14 UTC, nkshirsagar commented on hotsos/defs/scenarios/kernel/kernlog_calltrace.yaml
> +        {numreports} reports of antivirus related fanotify related hang in kern.log
done thanks

2023-05-17 10:36 UTC, mustafakemalgilor approved these changes

2023-05-17 13:17 UTC, merged