Check for ovn northd version mismatch
canonical/hotsos pull request #768
Opened 2023-11-01 12:29 UTC by dosaboy

If the versions are from the same major release
and ovn-match-northd-version='true' in the local
db then we can suggest setting
ovn-match-northd-version='false' to unblock the
controller. Also adds a scenario to warn if
ovn-match-northd-version is set to true since
this should only be the case during a major release upgrade.

Resolves: #763

2023-11-01 14:50 UTC, dosaboy commented
need to ref https://bugs.launchpad.net/charm-ovn-chassis/+bug/2030944 in the checks

2023-11-01 14:50 UTC, brianphaley requested changes
Review not done, just partial

2023-11-01 18:19 UTC, alanbach reviewed
I went over the changes and they look good to me. Once merged and we have a test build, I can try this out in my home-lab.

Thank you so much for implementing this!

2023-11-01 19:14 UTC, brianphaley requested changes

2023-11-01 19:14 UTC, brianphaley commented on hotsos/defs/scenarios/openvswitch/ovn/ovn_upgrades.yaml
> +        will cause unnecessary errors if a minor release upgrade of ovn packages is
nit: s/ovn/OVN

2023-11-01 19:14 UTC, brianphaley commented on hotsos/plugin_extensions/openvswitch/event_checks.py
> +                       "external-ids:{dbkey}=\"false\"".
I think there is a missing ' here to match the one from 'ovs-vsctl

2023-11-01 19:14 UTC, brianphaley commented on hotsos/defs/scenarios/openvswitch/ovn/ovn_upgrades.yaml
> +        Open_vSwitch . external-ids:{dbkey}="false"
nit: should put the ovs-vsctl command inside ' ' if possible

2023-11-01 19:14 UTC, brianphaley commented on tests/unit/test_openvswitch.py
> +               "external-ids:ovn-match-northd-version=\"false\"")
Missing closing ' here too

2023-11-01 19:14 UTC, brianphaley commented on hotsos/defs/tests/scenarios/openvswitch/ovn/ovn_upgrades_no_mismatch_dbflag_set.yaml
> +    Open_vSwitch . external-ids:ovn-match-northd-version="false"
Same comment here regarding putting this in ' '

2023-11-01 21:26 UTC, merged

2023-11-02 08:28 UTC, jrodrigu-canonical commented
For the newly deployed nova-compute on an existing OVN setup, you would get the following warning from hotsos:

`OVN controller is reporting a version mismatch between itself (22.03.3-20.21.0-62.4) and northd (22.03.0-20.21.0-58.3). This usually means ovn-central (ovn-northd etc) services have been upgraded before ovn-controller using a version of ovn that does not support this. To fix this issue you may need to upgrade ovn-controller on this host (current=22.03.3-0ubuntu0.22.04.1~cloud0).`

In this scenario, this would mean that ovn-controller was upgraded to a higher minor version than ovn-central. And the fix would be to upgrade ovn-central to 22.03.3 or set external-ids:ovn-match-northd-version="false"

As far as I can see, we can have 4 scenarios with OVN versions:

1. ovn-central has a greater major version than ovn-controller: the fix is to upgrade ovn-controller to the same major version
2. ovn-controller has a greater major version than ovn-central: the fix is to upgrade ovn-central to the same major version
3. ovn-central has a greater minor version than ovn-controller: the fix is to set external-ids:ovn-match-northd-version="false", or upgrade ovn-controller to the same version
4. ovn-controller has a greater minor version than ovn-central: the fix is to set external-ids:ovn-match-northd-version="false", or upgrade ovn-central to the same version

2023-11-02 09:14 UTC, dosaboy commented
hmm thats odd i was actually expecting it to match https://github.com/canonical/hotsos/blob/a9a33d906035e77124f6d9c57a8fb8ffade8a192/hotsos/defs/scenarios/openvswitch/ovn/ovn_upgrades.yaml#L41 in this case. I will look into why that is happening.

2023-11-02 09:18 UTC, dosaboy commented
hmm thats odd i was actually expecting it to match https://github.com/canonical/hotsos/blob/a9a33d906035e77124f6d9c57a8fb8ffade8a192/hotsos/defs/scenarios/openvswitch/ovn/ovn_upgrades.yaml#L41 in this case. I will look into why that is happening.

2023-11-02 09:31 UTC, dosaboy commented
@jrodrigu-canonical turns out turns out the output you got was from a previous version i.e. did not have this patch. if you update your hotsos snap/package to the latest (i just released the stable snap) you should get the new behaviour.