Replace deprecated property `not_valid_after`
canonical/hotsos pull request #788
Opened 2024-02-20 21:32 UTC by nicolasbock

This change replaces the deprecated `not_valid_after` property with the
timezone aware `not_valid_after_utc` [1].

[1] https://cryptography.io/en/latest/x509/reference/#cryptography.x509.Certificate.not_valid_after

Closes: https://github.com/canonical/hotsos/issues/785
Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>

2024-02-22 16:57 UTC, brianphaley requested changes

2024-02-22 16:57 UTC, brianphaley commented on hotsos/core/host_helpers/ssl.py
> +        print(f"tzinfo: {today.tzinfo}")
Leftover debug?

2024-02-22 17:27 UTC, nicolasbock commented on hotsos/core/host_helpers/ssl.py
> +        print(f"tzinfo: {today.tzinfo}")
Oops, yes :/

2024-02-22 17:43 UTC, brianphaley approved these changes

2024-02-28 12:24 UTC, dosaboy commented
@nicolasbock thanks for the patch this is all good. only nit is that the patch mostly contains github workflow updates and the commit message has no mention of that. Can you either split the patch in two or update the commit msg to reflect that?

2024-02-28 12:27 UTC, dosaboy commented
@nicolasbock my apologies, i didnt update my branch properly, this is totally fine

2024-02-28 12:27 UTC, merged