Add dpdk config checks
canonical/hotsos pull request #802
Opened 2024-04-09 11:36 UTC by dosaboy

Checks that Open_vSwitch table contains expected config for pmd and logical cores.

Resolves: #636

2024-04-09 22:49 UTC, brianphaley requested changes
Just a typo. Thanks for picking this up, completely forgot about it.

2024-04-09 22:49 UTC, brianphaley commented on hotsos/defs/tests/scenarios/openvswitch/dpdk_config_fail.yaml
> +    OpenvSwitch DPDK is enabled on this host but one ore more of 'pmd-cpu-mask,
s/ore/or

2024-04-09 22:49 UTC, brianphaley commented on hotsos/defs/tests/scenarios/openvswitch/dpdk_config_fail_mask_overlap.yaml
> +    OpenvSwitch DPDK is enabled on this host but one ore more core exists in
s/ore/or

2024-04-09 22:49 UTC, brianphaley commented on hotsos/defs/scenarios/openvswitch/dpdk_config.yaml
> +        OpenvSwitch DPDK is enabled on this host but one ore more of
s/ore/or

2024-04-09 22:49 UTC, brianphaley commented on hotsos/defs/scenarios/openvswitch/dpdk_config.yaml
> +        OpenvSwitch DPDK is enabled on this host but one ore more core exists
s/ore/or

2024-04-11 00:07 UTC, brianphaley approved these changes

2024-04-11 13:05 UTC, dosaboy commented
i had a discussion with @peppepetra about other checks we could add and he reminded me that we need to ensure pmd-cpu-mask does not overlay with nova cpu-dedicated-set cpus (which is actually mentioned in the issue). I will create a followup patch to add this.

2024-04-11 13:05 UTC, merged